# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0buserservice\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x12\n\x10ListUsersRequest\"B\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"N\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t2\xe2\x01\n\x0bUserService\x12\x41\n\x07GetUser\x12\x1b.userservice.GetUserRequest\x1a\x19.userservice.UserResponse\x12G\n\tListUsers\x12\x1d.userservice.ListUsersRequest\x1a\x19.userservice.UserResponse0\x01\x12G\n\nCreateUser\x12\x1e.userservice.CreateUserRequest\x1a\x19.userservice.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERREQUEST']._serialized_start=35
  _globals['_GETUSERREQUEST']._serialized_end=68
  _globals['_LISTUSERSREQUEST']._serialized_start=70
  _globals['_LISTUSERSREQUEST']._serialized_end=88
  _globals['_CREATEUSERREQUEST']._serialized_start=90
  _globals['_CREATEUSERREQUEST']._serialized_end=156
  _globals['_USERRESPONSE']._serialized_start=158
  _globals['_USERRESPONSE']._serialized_end=236
  _globals['_USERSERVICE']._serialized_start=239
  _globals['_USERSERVICE']._serialized_end=465
# @@protoc_insertion_point(module_scope)
